import Head from 'next/head';
import Mynotes from './Mynotes';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className='flex h-full flex-col justify-center items-center'></div>
    </div>
  );
};